swagger: "2.0"
info:
  version: "0.0.1"
  title: Medias Center Backend
host: localhost:10010
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /medias:
    x-swagger-router-controller: medias
    get:
      description: Returns all medias properties to the caller, without any pagination.
      operationId: getAllMedias
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AllMediasResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/MediasErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  Media:
    type: object
    required:
      - path
    properties:
      path:
        type: string
  EmptyObject:
    type: object
  AllMediasResponse:
    type: array
    items:
      $ref: "#/definitions/Media"
  MediasErrorResponse:
      type: array
      items:
        $ref: "#/definitions/EmptyObject"